### PR TITLE
Inherit link fontFamily and color

### PR DESCRIPTION
**Pull request by diegomura**

### CODE REVIEW

**Comment by diegomura** [comment]
I'm not merging this yet because `inherit` as value is not supported yet.
Currently there is a inheritance system builded on react-pdf, that takes some of the parent styles if some attributes are not present. However, there is also some default styling attributes for some of the elements (including text blue for Links) which has preference over the inheritance. So what's left to do is having the ability to manually set inheritance on styles

**Comment by diegomura** [comment]
**Update**
@tpreusse  here https://github.com/orbiting/pdf/pull/56 you mention that links should be always black. From our talk this morning I had the idea that should take the parent's color (probably black in most cases).
Is it enough for our use case if we set it up as black for the moment and tackle this in another time?

**Comment by tpreusse** [comment]
@diegomura yeah static black is good for now

**Comment by diegomura** [comment]
Awesome. This is already done. Closing this

**Pull request closed without merging**
